//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYanShiYuDing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShiYanShiEntities : DbContext
    {
        public ShiYanShiEntities()
            : base("name=ShiYanShiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_ShiYanShi> M_ShiYanShi { get; set; }
        public virtual DbSet<M_ZuoWei> M_ZuoWei { get; set; }
        public virtual DbSet<T_ShiYanShiBuKeYongShiJian> T_ShiYanShiBuKeYongShiJian { get; set; }
        public virtual DbSet<T_YuYue> T_YuYue { get; set; }
    }
}
