//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYanShiYuDing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ShiYanShiBuKeYongShiJian
    {
        public int zidongbianhao { get; set; }
        public int zhouji { get; set; }
        public System.DateTime kaishiriqi { get; set; }
        public System.DateTime jieshuriqi { get; set; }
        public System.DateTime gengxinriqi { get; set; }
    
        public virtual M_ShiYanShi M_ShiYanShi { get; set; }
    }
}
