//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYanShiYuDing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YuYue
    {
        public int zidongbianhao { get; set; }
        public string jiaoshibianhao { get; set; }
        public string xueshengbianhao { get; set; }
        public System.DateTime yuyuekaishiriqi { get; set; }
        public System.DateTime yuyuejieshuriqi { get; set; }
        public System.DateTime gengxinriqi { get; set; }
        public string xiangmu { get; set; }
        public string zhidaojiaoshi { get; set; }
        public string banji { get; set; }
        public string xueshengxingming { get; set; }
    
        public virtual M_ShiYanShi M_ShiYanShi { get; set; }
        public virtual M_ZuoWei M_ZuoWei { get; set; }
    }
}
