//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYanShiYuDing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ZuoWei
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ZuoWei()
        {
            this.T_YuYue = new HashSet<T_YuYue>();
        }
    
        public int zidongbianhao { get; set; }
        public string zuoweimingcheng { get; set; }
        public Nullable<bool> shifoutingyong { get; set; }
        public bool shifoushanchu { get; set; }
        public System.DateTime gengxinriqi { get; set; }
        public Nullable<int> zhuohao { get; set; }
    
        public virtual M_ShiYanShi M_ShiYanShi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_YuYue> T_YuYue { get; set; }
    }
}
