//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiYanShiYuDing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YuYue
    {
        public int zidongbianhao { get; set; }
        public string jiaoshibianhao { get; set; }
        public string xueshengbianhao { get; set; }
        public System.DateTime yuyuekaishiriqi { get; set; }
        public System.DateTime yuyuejieshuriqi { get; set; }
        public System.DateTime gengxinriqi { get; set; }
        public string xiangmu { get; set; }
        public string zhidaojiaoshi { get; set; }
        public string banji { get; set; }
        public string xueshengxingming { get; set; }
    
        public virtual M_ShiYanShi M_ShiYanShi { get; set; }
        public virtual M_ZuoWei M_ZuoWei { get; set; }
    }
}
